spring:
  application:
    name: travel-web
  datasource:
    url: jdbc:mysql://localhost:3306/travel?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 19990421Hzhf
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl  # ← 移到这里
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
  sql:
    init:
      mode: never
  thymeleaf:
    cache: false

server:
  port: 8080
  servlet:
    session:
      cookie:
        name: TRAVELSESSION

logging:
  level:
    org.hibernate.SQL: warn